### ISSUE TITLE
有A/B测试的demo吗？

### ISSUE THREAD

**Issue by Jdb156158** [AppGalleryConnect/agc-ios-demos#1]
我在华为开发者联盟后台按照指南操作了一圈，但是一直没有搞好，我们不知道怎么让A/B测试和远程配置SDK还有统计SDK这些配合起来使用。他们之间操作的联系是什么。比我就像使用在某个详细的页面测试两个按钮的点击率。该怎么操作啊

**Comment by Mayism** [comment]
@Jdb156158 不好意思哈 AB测试是操作类的服务 是没有demo的 你可以配合远程配置的demo和[AB测试的使用指导](https://developer.huawei.com/consumer/cn/doc/development/AppGallery-connect-Guides/agc-abtest-remoteconfig-0000001058442248) 进行操作
